apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
stringData:
  api-token: w5lYx1xLlXEIbxMv7xsEas9T1VaK2iAtfLwwI6Ro
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer 
spec:
  acme:
    email: iveoname@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: iveoname@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
